# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocyclo
    - dupl
    - goconst

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
