#!/bin/bash
# Platform Deployment Reference Script
# This script shows platform team how to deploy all required services
# Adapt this for your production platform deployment

set -euo pipefail

NAMESPACE="${NAMESPACE:-observability}"
TRAEFIK_NAMESPACE="${TRAEFIK_NAMESPACE:-traefik-system}"

echo "=========================================="
echo "  Platform Services Deployment Reference"
echo "=========================================="
echo "This script shows commands to deploy platform services"
echo "Adapt these commands for your production platform"
echo ""
echo "Namespace: $NAMESPACE"
echo "Traefik Namespace: $TRAEFIK_NAMESPACE"
echo ""

# Add all Helm repositories
echo "Step 1: Adding Helm repositories..."
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add grafana https://grafana.github.io/helm-charts
helm repo add traefik https://traefik.github.io/charts
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo update
echo "✓ Repositories added"
echo ""

# Create namespace
echo "Step 2: Creating namespace..."
kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
echo "✓ Namespace created"
echo ""

echo "=========================================="
echo "  Platform Services Installation Commands"
echo "=========================================="
echo ""
echo "# 1. Prometheus + Prometheus Operator + Grafana"
echo "helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \\"
echo "  --namespace $NAMESPACE \\"
echo "  --version 58.0.0 \\"
echo "  --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \\"
echo "  --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false \\"
echo "  --set prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues=false \\"
echo "  --set prometheus.prometheusSpec.retention=30d \\"
echo "  --wait"
echo ""

echo "# 2. Loki (Standalone - for OTel Collector)"
echo "helm upgrade --install loki grafana/loki \\"
echo "  --namespace $NAMESPACE \\"
echo "  --version 6.12.0 \\"
echo "  --wait"
echo ""

echo "# 3. Grafana Tempo"
echo "helm upgrade --install tempo grafana/tempo \\"
echo "  --namespace $NAMESPACE \\"
echo "  --version 1.7.0 \\"
echo "  --set serviceAccount.create=true \\"
echo "  --wait"
echo ""

echo "# 4. OpenTelemetry Collector"
echo "helm upgrade --install otel-collector open-telemetry/opentelemetry-collector \\"
echo "  --namespace $NAMESPACE \\"
echo "  --version 0.96.0 \\"
echo "  --wait"
echo ""

echo "# 5. Traefik (Optional - for Ingress)"
echo "kubectl create namespace $TRAEFIK_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -"
echo "helm upgrade --install traefik traefik/traefik \\"
echo "  --namespace $TRAEFIK_NAMESPACE \\"
echo "  --version 28.0.0 \\"
echo "  --set ingressClass.enabled=true \\"
echo "  --set ingressClass.isDefaultClass=true \\"
echo "  --wait"
echo ""

echo "# 6. Gateway API CRDs (Optional - if using Gateway API)"
echo "kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml"
echo ""

echo "=========================================="
echo "  Service Endpoints Applications Will Reference"
echo "=========================================="
echo ""
echo "OTel Collector:"
echo "  OTLP gRPC: otel-collector.$NAMESPACE.svc.cluster.local:4317"
echo "  OTLP HTTP: otel-collector.$NAMESPACE.svc.cluster.local:4318"
echo "  Prometheus: otel-collector.$NAMESPACE.svc.cluster.local:8889/metrics"
echo ""
echo "Prometheus:"
echo "  Query API: prometheus-kube-prometheus-prometheus.$NAMESPACE.svc.cluster.local:9090"
echo "  Operator Namespace: $NAMESPACE (for ServiceMonitor deployment)"
echo ""
echo "Loki:"
echo "  Push API: loki.$NAMESPACE.svc.cluster.local:3100/loki/api/v1/push"
echo "  Query API: loki.$NAMESPACE.svc.cluster.local:3100"
echo ""
echo "Tempo:"
echo "  OTLP gRPC: tempo.$NAMESPACE.svc.cluster.local:4317"
echo "  OTLP HTTP: tempo.$NAMESPACE.svc.cluster.local:4318"
echo "  Query API: tempo.$NAMESPACE.svc.cluster.local:3200"
echo ""
echo "Grafana:"
echo "  UI: grafana.$NAMESPACE.svc.cluster.local:80"
echo "  Dashboard Namespace: $NAMESPACE (for ConfigMap deployment)"
echo ""
echo "=========================================="
echo "  OTel Collector Service Labels (for ServiceMonitor)"
echo "=========================================="
echo ""
echo "Applications will create ServiceMonitors that select OTel Collector."
echo "Ensure OTel Collector service has one of these label sets:"
echo ""
echo "Default labels:"
echo "  component: otel-collector"
echo ""
echo "OR platform-specific labels:"
echo "  app.kubernetes.io/name: opentelemetry-collector"
echo "  app.kubernetes.io/component: collector"
echo ""
echo "Applications configure this via:"
echo "  monitoring.serviceMonitor.otelCollector.selectorLabels"
echo ""
echo "=========================================="
echo "  Complete Documentation"
echo "=========================================="
echo ""
echo "See docs/PLATFORM_DEPENDENCIES.md for complete details:"
echo "  - All Helm chart repositories and versions"
echo "  - Recommended production configurations"
echo "  - Service endpoint references"
echo "  - Troubleshooting guide"
echo ""
